tap "homebrew/bundle"

brew "actionlint"
brew "bat"
brew "cloc"
brew "fzf"
brew "gemini-cli"
brew "gh"
brew "ghq"
brew "imagemagick"
brew "jq"
brew "openssl@3", link: true
brew "peco"
brew "ripgrep"
brew "sops"
brew "tmux"
brew "tree"

cask "brave-browser"
cask "claude-code"
cask "codex"
cask "cursor"
cask "docker-desktop"
cask "karabiner-elements"
cask "logi-options+"
cask "raycast"
cask "thebrowsercompany-dia"
cask "visual-studio-code"
cask "warp"
